version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: destiny2jobs
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

